// VoiceIt cross-platform desktop build.
//
// Builds the Tauri desktop app + bundled Python server sidecar and archives the
// platform installers (Linux .deb, macOS .dmg, Windows NSIS .exe). The bundles
// are large (~2.7 GB — the PyInstaller sidecar packs torch + the TTS engines),
// so one installer type per platform keeps compression time sane.
//
// Updater artifacts are disabled for CI (scripts/ci-disable-updater.py): the
// conf pins an updater pubkey + createUpdaterArtifacts, which otherwise makes
// tauri block on a signing-key password prompt and error when the bundle target
// isn't updater-enabled (e.g. .deb).
//
// Agent toolchains:
//   Linux  `pockeo-linux`   — /home/jenkins toolchains; `just` + python3 present.
//   macOS  `macos` (mbook)  — runs as jenkins; force HOME=/Users/jenkins; Python
//                              3.12 via uv (brew unwritable); bun in workspace home.
//                              Installs MLX (Apple-Silicon accel) + ad-hoc signs the
//                              .dmg so Gatekeeper shows the normal trust prompt.
//   Windows `pockeo-windows`— cmd/`bat` (the `powershell` step isn't on PATH there);
//                              uv + bun pre-provisioned; Python 3.12 via uv.

pipeline {
    agent none

    options {
        timestamps()
        timeout(time: 180, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '15'))
        disableConcurrentBuilds()
    }

    environment {
        CARGO_TERM_COLOR = 'always'
        RUST_BACKTRACE = '1'
        CI = 'true'
    }

    stages {
        stage('Build') {
            failFast false
            parallel {

                // ─── Linux (.deb) ───────────────────────────────────────────
                stage('Linux') {
                    agent { label 'pockeo-linux' }
                    steps {
                        sh '''
                            set -eu
                            export PATH="$HOME/.cargo/bin:$HOME/.bun/bin:$HOME/.local/bin:$PATH"
                            command -v bun  >/dev/null 2>&1 || curl -fsSL https://bun.sh/install | bash
                            export PATH="$HOME/.bun/bin:$PATH"
                            command -v just >/dev/null 2>&1 || cargo install just --locked
                            rustc --version; bun --version; just --version; python3 --version

                            # Warm workspaces can carry a stale backend/venv whose interpreter
                            # shebang points at an old path (e.g. after a job/workspace rename),
                            # which breaks `just setup`'s setup-python with a bad-interpreter error.
                            # Recreate it from scratch (macOS stage already does this).
                            rm -rf backend/venv
                            # Drop stale Tauri ACL codegen: a bundle-identifier/config change can
                            # leave the warm target/ with mismatched autogenerated permission tomls
                            # ("failed to read plugin permissions … app_hide.toml"). Forcing the
                            # tauri build script to re-run regenerates them.
                            rm -rf tauri/src-tauri/target/*/build/tauri-* tauri/src-tauri/target/*/.fingerprint/tauri-* 2>/dev/null || true

                            just setup
                            # The default (CPU) sidecar must NOT ship the ~2.7GB CUDA/NVIDIA
                            # libs that plain `torch` pulls on Linux (torch x.y+cuNNN). Swap to
                            # CPU torch + drop orphaned nvidia-* wheels so the .deb is ~0.5GB
                            # not 2.5GB. (CUDA users get the separate voiceit-server-cuda.)
                            backend/venv/bin/pip install --index-url https://download.pytorch.org/whl/cpu --force-reinstall torch torchaudio
                            backend/venv/bin/pip freeze | grep -iE '^nvidia[-_]' | cut -d'=' -f1 | xargs -r backend/venv/bin/pip uninstall -y || true
                            just build-server
                            python3 scripts/ci-disable-updater.py
                            ( cd tauri && bun run tauri build --bundles deb < /dev/null )
                        '''
                    }
                    post {
                        success {
                            archiveArtifacts artifacts: 'tauri/src-tauri/target/release/bundle/deb/*.deb',
                                allowEmptyArchive: false, fingerprint: true
                        }
                        cleanup { sh 'rm -rf tauri/src-tauri/target/release/bundle || true' }
                    }
                }

                // ─── macOS (.dmg) ───────────────────────────────────────────
                stage('macOS') {
                    agent { label 'macos' }
                    steps {
                        sh '''
                            set -eu
                            export HOME=/Users/jenkins
                            export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/Users/jenkins/.nvm/versions/node/v24.14.1/bin:/Users/jenkins/.nvm/versions/node/v24.14.0/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
                            export BUN_INSTALL="$HOME/.bun"
                            command -v bun >/dev/null 2>&1 || curl -fsSL https://bun.sh/install | bash
                            export PATH="$BUN_INSTALL/bin:$PATH"
                            uv --version; rustc --version; bun --version

                            rm -rf backend/venv
                            uv venv --python 3.12 --seed backend/venv
                            backend/venv/bin/python -m pip install --upgrade pip
                            backend/venv/bin/pip install -r backend/requirements.txt
                            # Apple Silicon acceleration: without MLX the sidecar falls back to the
                            # generic PyTorch path (LLM on MPS, TTS on CPU) and runs slowly even on
                            # M-series. build_binary.py already bundles MLX on arm64 (--collect-all
                            # mlx/mlx_audio/mlx_lm) — it just needs the packages present in the venv.
                            # mlx-lm / mlx-audio declare transformers>=5.x (conflicts with our 4.57.x
                            # cap) so install them --no-deps; mirrors .github/workflows/release.yml.
                            backend/venv/bin/pip install -r backend/requirements-mlx.txt
                            backend/venv/bin/pip install --no-deps mlx-lm==0.31.1
                            backend/venv/bin/pip install --no-deps mlx-audio==0.4.1
                            bun install
                            ./scripts/build-server.sh
                            backend/venv/bin/python scripts/ci-disable-updater.py
                            # Drop stale Tauri ACL codegen from the warm target/ (a bundle-identifier
                            # change otherwise leaves mismatched autogenerated permission tomls →
                            # "failed to read plugin permissions … app_hide.toml"). Forces regen.
                            rm -rf tauri/src-tauri/target/*/build/tauri-* tauri/src-tauri/target/*/.fingerprint/tauri-* 2>/dev/null || true

                            # Ad-hoc code signing ("-"). The app was previously shipped fully
                            # unsigned, so Gatekeeper flagged it as "damaged"/unverifiable instead of
                            # the normal "unidentified developer → right-click Open" flow. Tauri reads
                            # APPLE_SIGNING_IDENTITY and signs the .app at build time so the copy
                            # inside the .dmg is signed too.
                            export APPLE_SIGNING_IDENTITY="-"
                            ( cd tauri && bun run tauri build --bundles dmg < /dev/null )

                            # Tauri already signed the .app with the ad-hoc identity ("-") above and
                            # bundled it into its OWN styled .dmg — drag-to-Applications symlink,
                            # background, Finder window layout, and a blessed .VolumeIcon.icns. Ship
                            # that dmg AS-IS. Do NOT rebuild it with `hdiutil create -srcfolder`: that
                            # strips the layout/background and the volume-icon bless, producing the
                            # bare, icon-less image we used to emit. Verify the signature only.
                            # (For a fully trusted, no-warning install, set a real Developer ID +
                            # APPLE_ID/APPLE_PASSWORD/APPLE_TEAM_ID and notarize the Tauri dmg here.)
                            DMG=$(find tauri/src-tauri/target/release/bundle/dmg -name "*.dmg" | head -1 || true)
                            APP=$(find tauri/src-tauri/target/release/bundle/macos -maxdepth 1 -name "*.app" -type d | head -1 || true)
                            if [ -n "$APP" ]; then
                                codesign --verify --deep --strict "$APP" && echo "Signature: OK" || echo "Signature: INVALID"
                                codesign -dvv "$APP" 2>&1 | grep -E "Signature|Identifier|Authority" || true
                            fi
                            [ -n "$DMG" ] && echo "=== Tauri styled dmg: $(du -h "$DMG" | cut -f1) ==="
                        '''
                    }
                    post {
                        success {
                            archiveArtifacts artifacts: 'tauri/src-tauri/target/release/bundle/dmg/*.dmg',
                                allowEmptyArchive: true, fingerprint: true
                        }
                        cleanup { sh 'rm -rf tauri/src-tauri/target/release/bundle || true' }
                    }
                }

                // ─── Windows (NSIS .exe) ────────────────────────────────────
                // cmd/bat (the Jenkins `powershell` step's launcher can't find
                // powershell.exe on these agents — PockeoR uses bat too). uv + bun
                // are pre-provisioned in C:\Users\pockeo.
                stage('Windows') {
                    agent { label 'pockeo-windows' }
                    options { retry(count: 2, conditions: [agent(), nonresumable()]) }
                    steps {
                        checkout scm
                        bat '''
                            set "PATH=%USERPROFILE%\\.local\\bin;%USERPROFILE%\\.cargo\\bin;%USERPROFILE%\\.bun\\bin;C:\\Program Files\\Git\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\nodejs;C:\\Strawberry\\perl\\bin;C:\\LLVM\\bin;%PATH%"
                            uv --version || exit /b 1
                            bun --version || exit /b 1
                            rustc --version || exit /b 1

                            if exist backend\\venv rmdir /S /Q backend\\venv
                            uv venv --python 3.12 --seed backend\\venv || exit /b 1
                            backend\\venv\\Scripts\\python.exe -m pip install --upgrade pip || exit /b 1
                            backend\\venv\\Scripts\\pip.exe install -r backend\\requirements.txt || exit /b 1
                            REM build-server.sh auto-installs PyInstaller on unix; do it explicitly here
                            backend\\venv\\Scripts\\pip.exe install pyinstaller || exit /b 1
                            REM CPU sidecar: swap CUDA torch for the CPU build (smaller + correct)
                            backend\\venv\\Scripts\\pip.exe install --index-url https://download.pytorch.org/whl/cpu --force-reinstall torch torchaudio || exit /b 1
                            call bun install || exit /b 1
                            backend\\venv\\Scripts\\python.exe scripts\\ci-disable-updater.py || exit /b 1

                            set "PATH=%CD%\\backend\\venv\\Scripts;%PATH%"
                            python backend\\build_binary.py || exit /b 1
                            for /f "delims=" %%i in ('rustc --print host-tuple') do set "TRIPLE=%%i"
                            if not exist tauri\\src-tauri\\binaries mkdir tauri\\src-tauri\\binaries
                            copy /Y backend\\dist\\voiceit-server.exe "tauri\\src-tauri\\binaries\\voiceit-server-%TRIPLE%.exe" || exit /b 1
                            python backend\\build_binary.py --shim || exit /b 1
                            copy /Y backend\\dist\\voiceit-mcp.exe "tauri\\src-tauri\\binaries\\voiceit-mcp-%TRIPLE%.exe" || exit /b 1

                            REM Drop stale Tauri ACL codegen / fingerprints. After the job + bundle-id
                            REM rename the warm target/ can reference the old workspace path and carry
                            REM mismatched autogenerated permission tomls ("failed to read plugin
                            REM permissions ... app_hide.toml"). Wiping build/ + .fingerprint forces regen.
                            if exist tauri\\src-tauri\\target\\release\\build rmdir /S /Q tauri\\src-tauri\\target\\release\\build
                            if exist tauri\\src-tauri\\target\\release\\.fingerprint rmdir /S /Q tauri\\src-tauri\\target\\release\\.fingerprint

                            cd tauri || exit /b 1
                            call bun run tauri build --bundles nsis || exit /b 1
                        '''
                    }
                    post {
                        success {
                            archiveArtifacts artifacts: 'tauri/src-tauri/target/release/bundle/nsis/*.exe',
                                allowEmptyArchive: true, fingerprint: true
                        }
                        cleanup {
                            bat 'if exist tauri\\src-tauri\\target\\release\\bundle rmdir /S /Q tauri\\src-tauri\\target\\release\\bundle'
                        }
                    }
                }
            }
        }
    }

    post {
        success { echo 'VoiceIt desktop bundles built (Linux .deb, macOS .dmg, Windows NSIS).' }
        failure { echo 'Build failed — see the per-platform stage logs above.' }
    }
}
